### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by tchurch88** [fyookball/electrum#431]
Created a new wallet from private keys... encrypted it with a password. That password works to unlock the wallet but when I go to export my private keys it will not accept the same password there, or anywhere else that requires a password in the wallet. 3.1.1

**Comment by tchurch88** [comment]
Still a mystery. I can open the wallet just fine with my password but nothing else accepts it. If I try to change the password I just get incorrect password warnings. 

Are there any console commands I can try? 

Any way to read the wallet info with another tool since I know the password?

**Comment by stachorsub** [comment]
I'm having exactly the same problem. Wallet opens fine, but all other password prompts produce error when using the wallet password, including sending... This happens in 3.1.2 as well. Any suggestions?

**Comment by yurkazaytsev** [comment]
@tchurch88 , @stachorsub can you share with me the next details:
1) what type of distribution of electron-cash do you use (i mean, distro from site, building from source etc)
2) what OS do you use (Windows, Linux, etc)

**Comment by tchurch88** [comment]
Windows distribution from the site.

Wallet was created with 3.1.1 and I am now on 3.1.2.

Tried with two computers, both Windows 10.

**Comment by stachorsub** [comment]
I have used the portable versions 3.1.1 and 3.1.2 (ElectronCash-3.1.2-PORTABLE.exe) from the site (https://www.electroncash.org/#download) on Win 7 64 bit.
Created default_wallet with [imorted_privkey] while claiming Bitcoin Cash from Bitcoin Core. The wallet has a password and is encrypted.

**Comment by tchurch88** [comment]
My wallet was created the exact same way as stachorsub.

**Comment by livestalker** [comment]
Same problem. How fix it?

**Comment by yurkazaytsev** [comment]
@livestalker will make a pull request soon.

**Comment by tamm2001** [comment]
I am also having this problem.  Created wallet from electrum private keys.  I can log in with password fine its when I try to send transaction I keep getting "incorrect password" error; I am using the same password I just logged in with.  Is there a way to temporarily disable password? Thanks.

**Comment by yurkazaytsev** [comment]
@tamm2001 the problem solved in the last commit. I suppose it remains in windows version. You can try to do this steps in the app console  for now (go to **view/show console** for it):
```
wallet.keystore.update_password(None,'your password here')
wallet.save_keystore()
```
Let me know if it helps

**Comment by tamm2001** [comment]
It worked!  Thank you!!

**Comment by livestalker** [comment]
Cool! It is work! Thanks!

**Comment by stachorsub** [comment]
@fyookball @yurkazaytsev ... the console commands suggestion above did not work for me using 3.1.2 on Windows or on iOS. Here is the trace I get when running the first update_password command:

Traceback (most recent call last):
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/keystore.py", line 164, in check_password
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/keystore.py", line 179, in export_private_key
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/address.py", line 162, in from_WIF_privkey
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/address.py", line 149, in privkey_from_WIF_privkey
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/address.py", line 612, in decode_check
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/address.py", line 576, in decode
  File "/Users/admin/Desktop/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/address.py", line 562, in char_value
electroncash.address.Base58Error: invalid base 58 character "0"

Is the fix #449 merged by @yurkazaytsev going to resolve the issue in v3.1.3?

**Comment by yurkazaytsev** [comment]
@stachorsub it should be resolved in v3.1.3. Let me know If it fails again in your case and we discover it again.

**Comment by stachorsub** [comment]
@yurkazaytsev thanks for the confirmation. Any chance of having access to a beta / pre-release version of 3.1.3 Windows software (or iOS or both)? I'd be keen to verify that the fix works ahead of the production release..

**Comment by yurkazaytsev** [comment]
@stachorsub  you can try to build it from source if you familiar with python and linux. Can yuo share the type of address you want to import? is it starts from 1?

**Comment by stachorsub** [comment]
@yurkazaytsev I was hoping to try an existing windows beta build.. Unfortunately I don't have the environment to build from python source. The address I imported indeed starts with 1. The issue I'm actually having is not the import, but sending the imported coins. I'm trying to send the coins which requires password validation and that is the part that is failing with "invalid password". In other words, I have imported/claimed some Bitcoin Cash, but I am unable to do anything else with it, due to the password validation issue.

**Comment by stachorsub** [comment]
@yurkazaytsev @fyookball quick update.. I built the windows 3.1.3 binaries from source with the latest updates/fixes done by @yurkazaytsev and I still get the same "Incorrect password" error when sending or trying to reset the wallet password. This error is preventing me from doing enything with the Bitcoin Cash in the wallet. The wallet balance is positive, history of imported/received BCH is there, but other than staring at it, there is not mych else I can do via Electron Cash. Can you guys help?

**Comment by stachorsub** [comment]
@yurkazaytsev @fyookball  final update.. I don't know why it worked this time, but using the compiled 3.1.3, I went back to my original backup of the wallet after claiming the coins, I used the above "keystore.update_password..." commands again... and MAGIC - it worked. I managed to send all balance from the "troubled privkey import" wallet to another standard Electron Cash wallet. All good now. Happy days.

**Comment by bsvrus** [comment]
I went to the password in my purse Electron cash portable (I have the amount there after the splitting of the cue balloons) and I want to transfer money (drove the address, amount, commission) I press and send the password as well as the input to the purse itself, but the password-message password appears . For the same password in the wallet came in, and I can not send money, what's going on?
